version: "3.8"

services:
  frontend:
    container_name: frontend
    build: './ui'
    ports:
      - 80:4201
    volumes:
      - ./ui:/app/ui
      - /app/ui/node_modules
    environment:
      - NODE_ENV=dev
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=dddapp
      - KEYCLOAK_CLIENT_ID=frontend
      - BACKEND_BASE_PATH=http://backend:3001
      - PORT=4201
    depends_on:
      - keycloak
      - backend

  backend:
    container_name: backend
    build: './api'
    ports:
      - 3001:3001
    volumes:
      - ./api:/app/api
      - /app/api/node_modules
    environment:
      - APP_NAME=dddapp
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=dddapp
      - PORT=3001
    depends_on:
      - keycloak

  keycloak:
    build: './infra/keycloak'
    container_name: keycloak
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - KEYCLOAK_IMPORT=/tmp/realm-dev.json
    volumes:
      - ./infra/keycloak/realm-dev.json:/tmp/realm-dev.json
    command: [ "-Dkeycloak.profile.feature.upload_scripts=enabled" ]
    depends_on:
      - postgres
      - mailhog

  postgres:
    image: postgres:13.0-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./infra/postgres:/docker-entrypoint-initdb.d

  prometheus:
    image: prom/prometheus:v2.22.0
    container_name: prometheus
    ports:
      - 5000:9090
    volumes:
      - prometheus:/prometheus
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:6.7.5
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
      - DS_PROMETHEUS=prometheus
    volumes:
      - ./infra/grafana/config.ini:/etc/grafana/config.ini
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
      - ./infra/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

  mailhog:
    container_name: mailhog
    build: './mail'
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  postgres:
  prometheus:
